### ISSUE TITLE
Customize for Julia

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/devcontainer-templates#1]
This repo at the moment is a fork of a generic template. The TODO here is that we need to change things so that there is _one_ Julia template in here.

This will replace the (now deprecated) julia devcontainer in VS Code. The general idea is that we have one template in here that simply installs the Julia devcontainer feature.

CC @eitsupi

**Comment by eitsupi** [comment]
Excellent!
I recently did something similar in R here rocker-org/devcontainer-templates#21

At the moment there are not many options in the Julia Feature, so something simpler should suffice.

**Comment by davidanthoff** [comment]
Ah, great, so you know exactly what to do :) So I'll just hope for a PR from you to this repo here to sort things out, ok?

**Comment by eitsupi** [comment]
Okay, I'll take a look at this tonight. (It's Monday morning here in Japan and I'm just getting on the bus to go to work.)

**Comment by eitsupi** [comment]
I opened the PR #2 and it seems working. (The only way I know of to check if Template is working properly is the CI...)

I think we can merge and release it for now.

**Comment by davidanthoff** [comment]
Agreed.
